# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'CodeBlox' do
    pod 'SwiftyJSON', '~> 2.1'
    pod 'Firebase', '>= 2.5.1'
end

